In [56]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [57]:
df = sns.load_dataset("iris")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [58]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
X = df.drop('species',axis =1)
y = df['species']

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [62]:
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=13)

In [63]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [64]:
model_knn.score(X_test,y_test)

1.0

In [65]:
from sklearn.svm import SVC
model_svm = SVC(gamma= 'auto')
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [66]:
model_svm.score(X_test,y_test)

1.0

NOW LETS USE GRID SEARCH CV

In [67]:
from sklearn.model_selection import GridSearchCV

In [68]:
classifier = GridSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear']
},cv=5,return_train_score=False)

In [69]:
classifier.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [70]:
classifier.cv_results_

{'mean_fit_time': array([0.00580649, 0.00461931, 0.00531816, 0.00421977, 0.00393291,
        0.00457325, 0.00503621, 0.00482721]),
 'std_fit_time': array([0.0009649 , 0.00063038, 0.00068212, 0.00088583, 0.00034276,
        0.00091122, 0.00100788, 0.00098906]),
 'mean_score_time': array([0.0038178 , 0.0038084 , 0.00386734, 0.00291753, 0.00323524,
        0.00296154, 0.00337481, 0.00377617]),
 'std_score_time': array([0.00053129, 0.00095679, 0.00066197, 0.00046566, 0.0007294 ,
        0.00050273, 0.0008283 , 0.00112032]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.95, 1.  , 0.95, 0.95, 0.95, 0.95, 0.95, 0.95]),
 'split1_test_score': array([0.9 , 0.9 , 0.8 , 0.85, 0.8 , 0.85, 0.8 , 0.85]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1.  , 1.  , 1.  , 1.  , 1.  , 0.95, 1.  , 1.  ]),
 'split4_test_score': array([0.95, 0.95, 1.  , 0.95, 0.95, 1.  , 1.  , 1.  ]),
 'mean_test_score': array([0.94, 0.95, 0.93, 0.93, 0.92, 0.93, 0.93, 0.94]),
 'std_test_score': array([0.03741657, 0.04472136, 0.07483315, 0.0509902 , 0.0678233 ,
        0.0509902 , 0.07483315, 0.05830952]),
 'rank_test_score': array([2, 1, 4, 6, 8, 6, 4, 3], dtype=int32)}

In [71]:
results = pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005806,0.000965,0.003818,0.000531,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.95,0.90,0.9,1.00,0.95,0.94,0.037417,2
1,0.004619,0.000630,0.003808,0.000957,1,linear,"{'C': 1, 'kernel': 'linear'}",1.00,0.90,0.9,1.00,0.95,0.95,0.044721,1
2,0.005318,0.000682,0.003867,0.000662,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,4
3,0.004220,0.000886,0.002918,0.000466,10,linear,"{'C': 10, 'kernel': 'linear'}",0.95,0.85,0.9,1.00,0.95,0.93,0.050990,6
4,0.003933,0.000343,0.003235,0.000729,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,0.95,0.92,0.067823,8
5,0.004573,0.000911,0.002962,0.000503,20,linear,"{'C': 20, 'kernel': 'linear'}",0.95,0.85,0.9,0.95,1.00,0.93,0.050990,6
6,0.005036,0.001008,0.003375,0.000828,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,4
7,0.004827,0.000989,0.003776,0.001120,30,linear,"{'C': 30, 'kernel': 'linear'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,3

In [73]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf             0.94
1        1       linear             0.95
2       10          rbf             0.93
3       10       linear             0.93
4       20          rbf             0.92
5       20       linear             0.93
6       30          rbf             0.93
7       30       linear             0.94

In [75]:
classifier2 = GridSearchCV((model_knn),{
    'n_neighbors' : [1,3,5,7,9,11,13,15],
    'weights' : ['uniform','distance']
},cv=10,return_train_score=False)

In [77]:
classifier2.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=KNeighborsClassifier(n_neighbors=13),
             param_grid={'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 15],
                         'weights': ['uniform', 'distance']})

In [78]:
classifier2.cv_results_

{'mean_fit_time': array([0.00261536, 0.00251935, 0.002531  , 0.00218034, 0.003496  ,
        0.00365171, 0.00426502, 0.00354915, 0.00388353, 0.003634  ,
        0.00559664, 0.0053066 , 0.00376132, 0.00379963, 0.00360413,
        0.00344737]),
 'std_fit_time': array([0.00023157, 0.00015235, 0.00041359, 0.00016565, 0.00056008,
        0.00068399, 0.00103801, 0.0002381 , 0.00099681, 0.00056317,
        0.00385718, 0.00314268, 0.00053025, 0.00083942, 0.00040028,
        0.00028448]),
 'mean_score_time': array([0.00383887, 0.00261803, 0.00347419, 0.00244572, 0.00548251,
        0.00413632, 0.00564487, 0.00383122, 0.00505548, 0.00375614,
        0.00859272, 0.00539358, 0.00545654, 0.00392478, 0.00516977,
        0.00373363]),
 'std_score_time': array([0.00035336, 0.00013675, 0.00017238, 0.00033234, 0.00123014,
        0.00080354, 0.0005353 , 0.00024969, 0.00038158, 0.00016201,
        0.0051635 , 0.00289586, 0.00148587, 0.00018846, 0.00078255,
        0.00024032]),
 'param_n_neighbors': masked_array(data=[1, 1, 3, 3, 5, 5, 7, 7, 9, 9, 11, 11, 13, 13, 15, 15],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'n_neighbors': 1, 'weights': 'uniform'},
  {'n_neighbors': 1, 'weights': 'distance'},
  {'n_neighbors': 3, 'weights': 'uniform'},
  {'n_neighbors': 3, 'weights': 'distance'},
  {'n_neighbors': 5, 'weights': 'uniform'},
  {'n_neighbors': 5, 'weights': 'distance'},
  {'n_neighbors': 7, 'weights': 'uniform'},
  {'n_neighbors': 7, 'weights': 'distance'},
  {'n_neighbors': 9, 'weights': 'uniform'},
  {'n_neighbors': 9, 'weights': 'distance'},
  {'n_neighbors': 11, 'weights': 'uniform'},
  {'n_neighbors': 11, 'weights': 'distance'},
  {'n_neighbors': 13, 'weights': 'uniform'},
  {'n_neighbors': 13, 'weights': 'distance'},
  {'n_neighbors': 15, 'weights': 'uniform'},
  {'n_neighbors': 15, 'weights': 'distance'}],
 'split0_test_score': array([1. , 1. , 0.9, 1. , 1. , 1. , 1. , 1. , 0.9, 1. , 1. , 1. , 0.9,
        1. , 1. , 1. ]),
 'split1_test_score': array([0.9, 0.9, 1. , 1. , 1. , 1. , 0.9, 0.9, 1. , 1. , 0.9, 0.9, 0.9,
        0.9, 0.9, 0.9]),
 'split2_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'split3_test_score': array([0.8, 0.8, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7,
        0.7, 0.7, 0.7]),
 'split4_test_score': array([0.8, 0.8, 0.9, 0.9, 0.9, 0.9, 1. , 1. , 1. , 1. , 0.9, 0.9, 0.9,
        0.9, 0.9, 0.9]),
 'split5_test_score': array([1. , 1. , 1. , 1. , 0.9, 1. , 0.9, 1. , 0.9, 0.9, 0.9, 1. , 0.9,
        1. , 1. , 1. ]),
 'split6_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'split7_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'split8_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'split9_test_score': array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9,
        0.9, 0.9, 0.9]),
 'mean_test_score': array([0.94, 0.94, 0.94, 0.95, 0.94, 0.95, 0.94, 0.95, 0.94, 0.95, 0.93,
        0.94, 0.92, 0.94, 0.94, 0.94]),
 'std_test_score': array([0.08      , 0.08      , 0.09165151, 0.09219544, 0.09165151,
        0.09219544, 0.09165151, 0.09219544, 0.09165151, 0.09219544,
        0.09      , 0.09165151, 0.08717798, 0.09165151, 0.09165151,
        0.09165151]),
 'rank_test_score': array([ 5,  5,  5,  1,  5,  1,  5,  1,  5,  1, 15,  5, 16,  5,  5,  5],
       dtype=int32)}

In [80]:
results2 = pd.DataFrame(classifier2.cv_results_)
results2

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,split5_test_score,split6_test_score,split7_test_score,split8_test_score,split9_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002615,0.000232,0.003839,0.000353,1,uniform,"{'n_neighbors': 1, 'weights': 'uniform'}",1.0,0.9,1.0,0.8,0.8,1.0,1.0,1.0,1.0,0.9,0.94,0.080000,5
1,0.002519,0.000152,0.002618,0.000137,1,distance,"{'n_neighbors': 1, 'weights': 'distance'}",1.0,0.9,1.0,0.8,0.8,1.0,1.0,1.0,1.0,0.9,0.94,0.080000,5
2,0.002531,0.000414,0.003474,0.000172,3,uniform,"{'n_neighbors': 3, 'weights': 'uniform'}",0.9,1.0,1.0,0.7,0.9,1.0,1.0,1.0,1.0,0.9,0.94,0.091652,5
3,0.002180,0.000166,0.002446,0.000332,3,distance,"{'n_neighbors': 3, 'weights': 'distance'}",1.0,1.0,1.0,0.7,0.9,1.0,1.0,1.0,1.0,0.9,0.95,0.092195,1
4,0.003496,0.000560,0.005483,0.001230,5,uniform,"{'n_neighbors': 5, 'weights': 'uniform'}",1.0,1.0,1.0,0.7,0.9,0.9,1.0,1.0,1.0,0.9,0.94,0.091652,5
5,0.003652,0.000684,0.004136,0.000804,5,distance,"{'n_neighbors': 5, 'weights': 'distance'}",1.0,1.0,1.0,0.7,0.9,1.0,1.0,1.0,1.0,0.9,0.95,0.092195,1
6,0.004265,0.001038,0.005645,0.000535,7,uniform,"{'n_neighbors': 7, 'weights': 'uniform'}",1.0,0.9,1.0,0.7,1.0,0.9,1.0,1.0,1.0,0.9,0.94,0.091652,5
7,0.003549,0.000238,0.003831,0.000250,7,distance,"{'n_neighbors': 7, 'weights': 'distance'}",1.0,0.9,1.0,0.7,1.0,1.0,1.0,1.0,1.0,0.9,0.95,0.092195,1
8,0.003884,0.000997,0.005055,0.000382,9,uniform,"{'n_neighbors': 9, 'weights': 'uniform'}",0.9,1.0,1.0,0.7,1.0,0.9,1.0,1.0,1.0,0.9,0.94,0.091652,5
9,0.003634,0.000563,0.003756,0.000162,9,distance,"{'n_neighbors': 9, 'weights': 'distance'}",1.0,1.0,1.0,0.7,1.0,0.9,1.0,1.0,1.0,0.9,0.95,0.092195,1
10,0.005597,0.003857,0.008593,0.005163,11,uniform,"{'n_neighbors': 11, 'weights': 'uniform'}",1.0,0.9,1.0,0.7,0.9,0.9,1.0,1.0,1.0,0.9,0.93,0.090000,15
11,0.005307,0.003143,0.005394,0.002896,11,distance,"{'n_neighbors': 11, 'weights': 'distance'}",1.0,0.9,1.0,0.7,0.9,1.0,1.0,1.0,1.0,0.9,0.94,0.091652,5
12,0.003761,0.000530,0.005457,0.001486,13,uniform,"{'n_neighbors': 13, 'weights': 'uniform'}",0.9,0.9,1.0,0.7,0.9,0.9,1.0,1.0,1.0,0.9,0.92,0.087178,16
13,0.003800,0.000839,0.003925,0.000188,13,distance,"{'n_neighbors': 13, 'weights': 'distance'}",1.0,0.9,1.0,0.7,0.9,1.0,1.0,1.0,1.0,0.9,0.94,0.091652,5
14,0.003604,0.000400,0.005170,0.000783,15,uniform,"{'n_neighbors': 15, 'weights': 'uniform'}",1.0,0.9,1.0,0.7,0.9,1.0,1.0,1.0,1.0,0.9,0.94,0.091652,5
15,0.003447,0.000284,0.003734,0.000240,15,distance,"{'n_neighbors': 15, 'weights': 'distance'}",1.0,0.9,1.0,0.7,0.9,1.0,1.0,1.0,1.0,0.9,0.94,0.091652,5

In [81]:
results2[['param_n_neighbors','param_weights','mean_test_score']]

    param_n_neighbors param_weights  mean_test_score
0                   1       uniform             0.94
1                   1      distance             0.94
2                   3       uniform             0.94
3                   3      distance             0.95
4                   5       uniform             0.94
5                   5      distance             0.95
6                   7       uniform             0.94
7                   7      distance             0.95
8                   9       uniform             0.94
9                   9      distance             0.95
10                 11       uniform             0.93
11                 11      distance             0.94
12                 13       uniform             0.92
13                 13      distance             0.94
14                 15       uniform             0.94
15                 15      distance             0.94